matrix:
  include:
    - language: python
      os:
        - linux
      install:
        - pip install -r document_retrieval/requirements.txt
        - pip install -r document_similarity/requirements.txt
        - pip install -r text_embeddings/requirements.txt
        - pip install -r entrypoint/requirements.txt
        - pip install pylint
      script:
        - pylint document_retrieval
        - pylint document_similarity
        - pylint text_embeddings
        - pylint entrypoint

    - language: bash
      os:
        - windows
        - linux
      before_script:
      - cd ./scripts
      - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx
      - cd ..
      script: bash scripts/bash_tests.sh